playframework/play-samples

- .github/settings.yml
- play-java-jpa-example/build.sbt
- play-java-starter-example/build.sbt
- play-scala-anorm-example/build.sbt
- play-scala-grpc-example/build.sbt
- play-scala-isolated-slick-example/build.sbt
- play-scala-macwire-di-example/build.sbt
- play-scala-slick-example/build.sbt
- play-scala-starter-example/build.sbt
```
Updated with template-control on 2019-05-08T02:26:39.357Z
/.github/settings.yml:
wrote /.github/settings.yml
**build.sbt:
libraryDependencies += "com.h2database" % "h2" % "1.4.197"
**build.sbt:
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.1" % Test
**build.sbt:
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.1" % Test
**build.sbt:
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.1" % Test
**build.sbt:
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.1" % Test
**build.sbt:
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.1" % Test
**build.sbt:
libraryDependencies += "org.scalatestplus.play" %% "scalatestplus-play" % "4.0.1" % Test …
```
> Upgrade branch 2.7.x using TemplateControl

- .travis.yml
- play-scala-tls-example/conf/ws.conf
- play-scala-tls-example/project/plugins.sbt
> [2.8] Fix play-scala-tls-example on Java 11

- play-scala-macwire-di-example/conf/routes
> Display favicon in browser (see #35 for details)

- play-java-chatroom-example/build.sbt
- play-java-compile-di-example/build.sbt
- play-java-dagger2-example/build.sbt
- play-java-ebean-example/build.sbt
- play-java-fileupload-example/build.sbt
- play-java-forms-example/build.sbt
- play-java-grpc-example/docs/build.sbt
- play-java-hello-world-tutorial/build.sbt
- play-java-jpa-example/build.sbt
- play-java-rest-api-example/build.sbt
- play-java-starter-example/build.sbt
- play-java-streaming-example/build.sbt
- play-java-streaming-example/conf/application.conf
- play-java-websocket-example/build.sbt
- play-scala-chatroom-example/build.sbt
- play-scala-compile-di-example/build.sbt
- play-scala-fileupload-example/build.sbt
- play-scala-forms-example/build.sbt
- play-scala-grpc-example/docs/build.sbt
- play-scala-hello-world-tutorial/build.sbt
- play-scala-isolated-slick-example/build.sbt
- play-scala-log4j2-example/build.sbt
- play-scala-macwire-di-example/build.sbt
- play-scala-rest-api-example/build.sbt
- play-scala-secure-session-example/build.sbt
- play-scala-slick-example/build.sbt
- play-scala-starter-example/build.sbt
- play-scala-streaming-example/build.sbt
- play-scala-tls-example/build.sbt
- play-scala-websocket-example/build.sbt
related https://github.com/playframework/playframework/issues/9845
> General review of samples pre GA release

- play-scala-rest-api-example/project/Common.scala
> Trivial: Fixed typo

- play-scala-grpc-example/build.sbt
- play-scala-grpc-example/ssl-play
> Bump akka-http Dependency Version to 10.1.12

- play-scala-chatroom-example/app/controllers/HomeController.scala
- play-scala-compile-di-example/test/ServerSpec.scala
- play-scala-macwire-di-example/app/models/package.scala
- play-scala-slick-example/app/models/Person.scala
- play-scala-websocket-example/app/controllers/StockSentiment.scala
> add explicit type annotations for implicit val

- play-java-hello-world-tutorial/app/views/tutorial.scala.html
add () mark, since
```
GET /hello controllers.HomeController.hello
```
can't route correctly
> Fix tutorial.scala.html: add () mark

- play-java-rest-api-example/build.sbt
- play-scala-rest-api-example/build.sbt
These are the last ones missing.
> Use Scala 2.13 everywhere

- .github/workflows/build-test.yml
> [2.8.x] Use v3 workflows

- play-java-ebean-example/build.sbt
- play-java-ebean-example/conf/ebean.properties
> [2.9.x] Remove jaxb-runtime and ebean.properties

- play-scala-chatroom-example/app/controllers/InputSanitizer.scala
- play-scala-chatroom-example/build.sbt
> [2.9.x] Update/jsoup 1.15.4 29

- play-scala-websocket-example/app/actors/UserActor.scala
- play-scala-websocket-example/app/actors/UserParentActor.scala
- play-scala-websocket-example/app/controllers/HomeController.scala
- play-scala-websocket-example/build.sbt
- play-scala-websocket-example/project/plugins.sbt
Currently facing a typing error on a function in file `UserActor` line 102.
> Migrate play scala websocket example to Scala 3

- .github/workflows/build-test.yml
- test.sh
Except for the grpc and the slick examples for now
> Turn on Scala 3 on CI

- play-java-telemetry-example/build.sbt
- play-java-telemetry-example/project/plugins.sbt
- play-scala-telemetry-example/build.sbt
- play-scala-telemetry-example/project/plugins.sbt
We don't test them with CI, because we don't have a commecial licence. We just keep them as demo from Lightbend, but I don't even know if they work. I am not doing anything with them.
> Add Scala 3 to Telemetry examples

- play-java-jpa-example/conf/META-INF/persistence.xml
- play-java-rest-api-example/conf/META-INF/persistence.xml
> Switch persistence.xml to Jakarta JPA

- play-java-dagger2-example/build.sbt
- play-java-rest-api-example/build.sbt
- play-java-rest-api-example/project/plugins.sbt
- play-java-telemetry-example/project/plugins.sbt
- play-scala-isolated-slick-example/build.sbt
- play-scala-rest-api-example/project/plugins.sbt
- play-scala-telemetry-example/project/plugins.sbt
> Dependency upgrades for the 2.9.x branch

- play-scala-isolated-slick-example/project/plugins.sbt
See https://github.com/flyway/flyway-sbt/issues/82#issuecomment-1636728997
> Downgrade h2, not compatible with flyway

- play-java-dagger2-example/build.sbt
- play-java-ebean-example/build.sbt
- play-java-jpa-example/build.sbt
- play-java-rest-api-example/build.sbt
- play-java-rest-api-example/project/plugins.sbt
- play-scala-chatroom-example/build.sbt
- play-scala-isolated-slick-example/project/plugins.sbt
- play-scala-log4j2-example/build.sbt
- play-scala-rest-api-example/project/plugins.sbt
* #429
* #428
* #427
* #424
* #421
* #430
> Dependency updates

- .github/workflows/build-test.yml
> Correct branch in workflow

- play-java-grpc-example/app/routers/HelloWorldRouter.java
- play-java-grpc-example/build.sbt
- play-java-grpc-example/project/plugins.sbt
- play-java-grpc-example/scripts/test-sbt
- play-scala-grpc-example/build.sbt
- play-scala-grpc-example/project/plugins.sbt
- play-scala-grpc-example/scripts/test-sbt
Depends on https://github.com/playframework/play-grpc/issues/402
> [2.8.x] Update Akka/Play gRPC

- play-java-grpc-example/app/routers/HelloWorldRouter.java
- play-java-grpc-example/build.sbt
- play-java-grpc-example/project/plugins.sbt
- play-scala-grpc-example/build.sbt
- play-scala-grpc-example/project/plugins.sbt
> [2.9.x] Update Akka/Play gRPC

- play-java-chatroom-example/README.md
- play-java-compile-di-example/README.md
- play-java-dagger2-example/README.md
- play-java-ebean-example/README.md
- play-java-fileupload-example/README.md
- play-java-forms-example/README.md
- play-java-hello-world-tutorial/README.md
- play-java-jpa-example/README.md
- play-java-pekko-cluster-example/README.md
- play-java-rest-api-example/README.md
- play-java-starter-example/README.md
- play-java-streaming-example/README.md
- play-java-websocket-example/README.md
- play-scala-anorm-example/README.md
- play-scala-chatroom-example/README.md
- play-scala-compile-di-example/README.md
- play-scala-fileupload-example/README.md
- play-scala-forms-example/README.md
- play-scala-hello-world-tutorial/README.md
- play-scala-isolated-slick-example/README.md
- play-scala-log4j2-example/README.md
- play-scala-macwire-di-example/README.md
- play-scala-rest-api-example/README.md
- play-scala-secure-session-example/README.md
- play-scala-slick-example/README.md
- play-scala-starter-example/README.md
- play-scala-streaming-example/README.md
- play-scala-websocket-example/README.md
> Oops! It's Pekko HTTP not Akka HTTP

- test-gradle.sh
> [2.9.x] We can test slick samples with Scala 3 in test-gradle.sh

- test-gradle.sh
> [3.0.x] We can test all Scala 3 in test-gradle.sh

- play-java-rest-api-example/README.md
- play-java-rest-api-example/gatling/src/test/scala/simulation/GatlingSpec.scala
- play-java-rest-api-example/project/plugins.sbt
- play-scala-rest-api-example/README.md
- play-scala-rest-api-example/docs/src/main/paradox/appendix.md
- play-scala-rest-api-example/gatling/src/test/scala/simulation/GatlingSpec.scala
- play-scala-rest-api-example/project/plugins.sbt
> Fix broken Gatling URL

- test-gradle.sh
> [2.9.x] akka not pekko

- .github/scala-steward.conf
> Add `[3.0.x] ` prefix to scala-steward PRs

- .github/workflows/build-test.yml
- play-scala-isolated-slick-example/build.sbt
- test.sh
- See comment https://github.com/playframework/play-samples/pull/396#issuecomment-2082174643
> [3.0.x] Make `test.sh` script fail when any command fails

- play-scala-streaming-example/app/controllers/HomeController.scala
- play-scala-streaming-example/app/controllers/ScalaCometController.scala
- play-scala-streaming-example/app/controllers/ScalaEventSourceController.scala
- play-scala-streaming-example/app/views/index.scala.html
- play-scala-streaming-example/app/views/main.scala.html
- play-scala-streaming-example/app/views/scalacomet.scala.html
- play-scala-streaming-example/app/views/scalaeventsource.scala.html
- play-scala-streaming-example/build.sbt
The similar changes as https://github.com/playframework/play-samples/pull/483
> Fix `play-scala-streaming-example`

- java/compile-di/gradle/libs.versions.toml
- java/fileupload/gradle/libs.versions.toml
- java/jpa/gradle/libs.versions.toml
- java/rest-api/gradle/libs.versions.toml
- java/streaming/gradle/libs.versions.toml
- java/websocket/gradle/libs.versions.toml
- scala/rest-api/gradle/libs.versions.toml
- scala/streaming/gradle/libs.versions.toml
- scala/websocket/gradle/libs.versions.toml
I missed some samples in #723 🤦‍♂️
> Update `org.playframework.play` to `v3.1.0-4009e5a0-SNAPSHOT` (was `3.0.*`)

- .github/workflows/build-test.yml
- play-scala-anorm-example/build.sbt
- test.sh
This reverts commit 88e51fda935359ee721fd3cf3a628369e0497396.
After anorm switched to Play 3 / Pekko.
> Revert "Temporary disable anorm example"

- .github/workflows/build-test.yml
> [3.0.x] Fix test workflow
