play-java-dagger2-example/scripts/script-helper, play-java-fileupload-example/scripts/script-helper, play-java-forms-example/scripts/script-helper, play-java-hello-world-tutorial/scripts/script-helper, play-java-rest-api-example/scripts/script-helper, play-java-streaming-example/scripts/script-helper, play-scala-hello-world-tutorial/scripts/script-helper, play-scala-log4j2-example/scripts/script-helper
I think that by switching some of the builds from "language: java" to
"language: scala" they're running with modern sbt-extras, which no
longer supports _JAVA_OPTIONS.
=> Switch to JVM_OPTS, from _JAVA_OPTIONS

play-java-rest-api-example/README.md, play-java-rest-api-example/build.sbt, play-java-rest-api-example/gatling/src/test/resources/logback.xml, play-java-rest-api-example/gatling/src/test/scala/simulation/GatlingSpec.scala, play-java-rest-api-example/project/plugins.sbt, play-java-rest-api-example/scripts/test-sbt, play-scala-rest-api-example/README.md, play-scala-rest-api-example/app/v1/post/PostRouter.scala, play-scala-rest-api-example/build.sbt, play-scala-rest-api-example/docs/src/main/paradox/appendix.md, play-scala-rest-api-example/gatling/src/test/resources/logback.xml, play-scala-rest-api-example/gatling/src/test/scala/simulation/GatlingSpec.scala, play-scala-rest-api-example/project/Common.scala, play-scala-rest-api-example/project/plugins.sbt, play-scala-rest-api-example/scripts/test-sbt, play-scala-rest-api-example/scripts/validate-gatling
Follow up to https://github.com/playframework/play-samples/pull/36.
=> Use Scala 2.13 in the REST samples

play-java-rest-api-example/app/views/index.scala.html
This is already correct on the scala counterpart.
=> Remove trailing slashes. Guide was misleading.

play-scala-isolated-slick-example/modules/slick/build.sbt
… Use object `slick.jdbc.H2Profile` instead of `slick.driver.H2Driver`'
Project (still) compiles, tests succeed and sample application runs.
=> fix warning 'warning: value H2Driver in package driver is deprecated (since 3.2)

play-java-rest-api-example/scripts/test-sbt, play-java-rest-api-example/test/it/IntegrationTest.java
This PR introduces multiple changes:
1. each test case uses a unique `title` and `body` on the data it creates. This is necessary because this is a stateful tests and assertions were being mixed up
2. assertions are more strict. Previous implementation would treat the response as a plain `String` and assert that contained the `body` substring. This assertion is wrong since the Play failure page (an HTML indicating the requested URI is missing) can be converted to a `String` and it also contains the substring `body`. 
3. Adds a test case to ensure `GET /v1/posts/` works. Equivalent to #48 but for the java sample.
This PR is currently not passing all the tests (tested in `2.8.0-M3` and `2.7.3`). The reason is a test expecting `GET /v1/posts/` (the requests includes a trailing slash) fails. …
=> Improves Java REST tests: unique Strings, negative assertions

.github/settings.yml
This fix the issue of missing settings https://github.com/probot/settings/issues/150, but also protect the branch. 
We were not using branch protection because we were updating it from templatecontrol. That's not the case anymore.
=>  Fix branch protection rules

play-java-starter-example/conf/application.conf, play-scala-log4j2-example/conf/application.conf, play-scala-starter-example/conf/application.conf
Even though #44 states we should replace these settings with Akka HTTP values, I think removing the Netty ones (Currently unused on those samples) is enough.
Fixes #44
=> Remove unused netty settings

play-scala-hello-world-tutorial/README.md
Now, command to check sbt version is "sbt sbtVersion"
I fixed play-scala-hello-world-tutorial/README.md.
=> fix command to check sbt version

play-scala-streaming-example/app/views/scalacomet.scala.html, play-scala-streaming-example/build.sbt, play-scala-streaming-example/test/controllers/EventSourceControllerSpec.scala, play-scala-streaming-example/test/controllers/ScalaCommentControllerSpec.scala
- Bump to Scala 2.13.3
- Fix warnings reported by this change (auto-application will no
longer be supported in Scala 3)
=> Bump Scala/ScalaTest dependencies

play-java-grpc-example/docs/src/main/paradox/locally.md, play-scala-grpc-example/docs/src/main/paradox/locally.md
The `ssl-play` script for those two projects got removed in #111.
=> Fix docs for grpc-examples

play-scala-log4j2-example/build.sbt
Updated log4j version to 2.17.0 for [CVE-2021-45105](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105) - https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45105
=> Updating log4j to 2.17 in docs, for CVE-2021-45105

play-java-chatroom-example/build.sbt, play-java-dagger2-example/build.sbt, play-java-ebean-example/build.sbt, play-java-forms-example/build.sbt, play-java-grpc-example/build.sbt, play-java-rest-api-example/build.sbt, play-java-starter-example/build.sbt, play-java-telemetry-example/build.sbt, play-scala-grpc-example/build.sbt, play-scala-isolated-slick-example/build.sbt, play-scala-slick-example/build.sbt, play-scala-tls-example/build.sbt, project/build.properties
As per title, done like so;
```
scalafix --rules=https://gist.githubusercontent.com/eed3si9n/57e83f5330592d968ce49f0d5030d4d5/raw/7f576f16a90e432baa49911c9a66204c354947bb/Sbt0_13BuildSyntax.scala $( find ./ -type f -name '*.sbt' )
```
=> Update to new sbt syntax to resolve deprecation warnings in compilation

play-scala-isolated-slick-example/scripts/test-sbt
Doesn't matter for CI but for local testing only. Flyway failed with an exception because the old db was still there, containing old flyway meta data, but flyway was upgraded...
=> Remove old h2 db before running tests to avoid problems with flyway

play-java-websocket-example/app/actors/UserActor.java, play-scala-websocket-example/app/actors/UserActor.scala
Fix for the context.stop bug described in https://discuss.lightbend.com/t/mergehub-is-not-cleaning-up-in-the-heap-area/9740
=> 2.7.x fix context stop

play-scala-slick-example/build.sbt
Test where failling because sbt ++$MATRIX_SCALA was defaulting to `2.12.x` instead of `2.13.x`. The version is now specified in the root and the subprojects.
=> Add scalaVersion setting to root project in play-scala-slick-example

test.sh
A new condition in the `test.sh` test script to ensure that the MATRIX_SCALA environment variable is defined
=> Env variable condition added to test script

play-scala-isolated-slick-example/build.sbt, play-scala-isolated-slick-example/modules/slick/src/main/scala/com/example/user/slick/JodaSupport.scala
To avoid implicit resolution conflicts, I have decided to mix-in a trait for supplying instances for Joda in the Table classes. I really want to mix in GenericJodaSupport provided by slick-joda-mapper. But GenericJodaSupport is a class, so I can't mix-in. I may modify slick-joda-mapper later. I think slick-joda-mapper's interface is not good.
=> Update slick-joda-mapper to 2.6.0

play-java-grpc-example/build.sbt, play-scala-grpc-example/build.sbt
Only for 2.9 branch, no backport.
https://hub.docker.com/_/eclipse-temurin/tags?page=1&name=11-alpine
=> Use `eclipse-temurin:11-alpine` docker image

play-scala-isolated-slick-example/.gitignore, play-scala-isolated-slick-example/build.sbt, play-scala-isolated-slick-example/scripts/test-sbt
Fixes
- [**playframework/discussions#12280:** Problem with play-samples/play-scala-isolated-slick-example](https://github.com/orgs/playframework/discussions/12280)
The problem is the flyway-sbt plugins comes with a very old flyway version which does not support h2 2.x yet... So when running `flyway/flywayMigrate` in `sbt` it uses that very old flyway version to generate the `test.mv.db` file, using H2 version 1.x (which the old flyway version depends on). However when starting `run` in sbt afterwards, the application now depends on H2 version 2.x which file format is not compatible anymore with its v1...
Hopefully this gets fixes soon:
- https://github.com/flyway/flyway-sbt/pull/91
- https://github.com/flyway/flyway-sbt/issues/90
- https://github.com/flyway/flyway-sbt/issues/82
=> Downgrade h2 database to make   play-scala-isolated-slick-example work

play-java-chatroom-example/conf/application.conf, play-java-jpa-example/conf/META-INF/persistence.xml, play-java-rest-api-example/conf/META-INF/persistence.xml, play-java-starter-example/conf/application.conf, play-scala-chatroom-example/conf/application.conf, play-scala-log4j2-example/conf/application.conf, play-scala-starter-example/conf/application.conf, play-scala-streaming-example/conf/application.conf, play-scala-websocket-example/conf/application.conf
See https://www.playframework.com/documentation/3.0.x/Migration27#play.filters.headers.contentSecurityPolicy-deprecated-for-CSPFilter
=> [3.0.x] Remove deprecated `contentSecurityPolicy` config + deprecated hibernate.dialect config

.github/dependabot.yml
Almost the same like
- #564
but for the main branch, which currently isn't the default branch in this repo. Assuming this branch will become the default branch one day, I already add the file here so we have it in place (and also don't forget about it).
=> Dependabot should upgrade GitHub actions workflows

.github/dependabot.yml
Similiar to
- #573
but #573 was against the `main` branch which currently is _not_ the default branch of this repo (#573 and the previous pr just prepared the main branch to become the default branch one day)
=> [3.0.x] Add prefix to Dependabot commit message / PR title

play-scala-isolated-slick-example/build.sbt, test.sh
- See comment https://github.com/playframework/play-samples/pull/396#issuecomment-2082174643
=> [2.9.x] Make `test.sh` script fail when any command fails

.github/workflows/build-test.yml, test.sh
- See comment https://github.com/playframework/play-samples/pull/396#issuecomment-2082174643
=> Make `test.sh` script fail when any command fails

.github/scala-steward.conf
Upgrading bootstrap would require manual work. I think for sample it does not matter which bootstrap version is used as long as the sample works.
=> Pin bootstrap in scala steward config

play-scala-websocket-example/app/assets/javascripts/index.coffee, play-scala-websocket-example/app/assets/stylesheets/main.less, play-scala-websocket-example/app/views/index.scala.html, play-scala-websocket-example/build.sbt, play-scala-websocket-example/conf/application.conf, play-scala-websocket-example/conf/logback.xml, play-scala-websocket-example/project/plugins.sbt, play-scala-websocket-example/test/controllers/WebSocketClient.java
- Alternative for #667
The example is not working because the js files can not be loaded because they violate the csp directives.
Play's default `script-src`  directive is [this one](https://github.com/playframework/playframework/blob/3.0.4/web/play-filters-helpers/src/main/resources/reference.conf#L210):
```
script-src = ${play.filters.csp.nonce.pattern} "'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:"
```
So for this example this will be rendered to following header:
```
Content-Security-Policy: base-uri 'none'; script-src 'nonce-1BANcXNZ6pGIEXrrAszpvw==' 'unsafe-inline' 'unsafe-eval' 'strict-dynamic' https: http:; default-src 'self'; object-src 'none'; connect-src 'self' ws://localhost:9000
```
So all we need to do is to add the nonce to the js files so they are allowed to …
=> Fix `play-scala-websocket-example` (missing csp nonce)

.github/dependabot.yml
This reverts commit 5967cd960441355d0594573509fd58da3dda79dd.
In favor of #696
=> Revert "Configure Dependabot for Gradle"

scala/chatroom/build.gradle, scala/chatroom/gradle/libs.versions.toml, scala/compile-di/build.gradle, scala/compile-di/gradle/libs.versions.toml, scala/fileupload/build.gradle, scala/fileupload/gradle/libs.versions.toml, scala/forms/build.gradle, scala/forms/gradle/libs.versions.toml, scala/hello-world/build.gradle, scala/hello-world/gradle/libs.versions.toml, scala/log4j2/build.gradle, scala/log4j2/gradle/libs.versions.toml, scala/macwire-di/build.gradle, scala/macwire-di/gradle/libs.versions.toml, scala/rest-api/build.gradle, scala/rest-api/gradle/libs.versions.toml, scala/secure-session/build.gradle, scala/secure-session/gradle/libs.versions.toml, scala/starter/build.gradle, scala/starter/gradle/libs.versions.toml, scala/streaming/build.gradle, scala/streaming/gradle/libs.versions.toml, scala/websocket/build.gradle, scala/websocket/gradle/libs.versions.toml
We don't need to use `scalatest-junit-runner` anymore.
ScalaTest has native support now https://www.scalatest.org/plus/junit5
=> [Gradle] Use ScalaTest + JUnit 5

play-scala-isolated-slick-example/build.sbt, play-scala-isolated-slick-example/project/plugins.sbt
https://github.com/sbt/flyway-sbt/releases/tag/v10.21.0
We can now revert
- #523
- #366
Also, flyway 9.21.2 [upgraded jackson to 2.15.2](https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html#ReleaseNotesforFlywayEngine-Flyway9.21.2(2023-08-22)), so we exclude that from flyway's dependencies to avoid running into an exception regarding `jackson-module-scala` incompabitle (2.14 play comes with vs 2.15)
=> [3.0.x] Upgrade flyway-sbt + flyway-core to 10.21.0

.github/workflows/build-test.yml
Look at 
- #582
- #581
These are more or less identical pull requests. However, if you look closer at #581 you will see it changed java 11 to 21.
Why this did not happen in #582 I don't know. So I guess 1) either it was forgotten to change it in #582 too or 2) it was a mistake to change it to 21 in #581.
Anyway, I think it's a good idea to just run against 17 and 21 and just drop 11 now (even though Play 3.0 and 2.9 still support 11). These are just example projects and some dependencies already require Java 17 (like flyway #780) - I think it's a good idea to show examples with latest dependencies even though they can not be used with Java 11.
=> [2.9.x] Test with Java 21 instead of 11

.github/workflows/build-test.yml, java/chatroom/build.gradle.kts, java/compile-di/build.gradle.kts, java/dagger2/build.gradle.kts, java/ebean/build.gradle.kts, java/fileupload/build.gradle.kts, java/forms/build.gradle.kts, java/hello-world/build.gradle.kts, java/jpa/build.gradle.kts, java/pekko-cluster/build.gradle.kts, java/rest-api/build.gradle.kts, java/starter/build.gradle.kts, java/streaming/build.gradle.kts, java/websocket/build.gradle.kts, scala/chatroom/build.gradle, scala/compile-di/build.gradle, scala/fileupload/build.gradle, scala/forms/build.gradle, scala/hello-world/build.gradle, scala/log4j2/build.gradle, scala/macwire-di/build.gradle, scala/rest-api/build.gradle, scala/secure-session/build.gradle, scala/starter/build.gradle, scala/streaming/build.gradle, scala/websocket/build.gradle, test.sh
@mkurz while you are reviewing my PRs to core repo I can do something useful for our samples 😄 
So, now we check a Netty backend for all Gradle samples.
Outside the CI Netty is default for Java examples, Pekko for Scala.
=> Check Netty backend for Gradle examples

play-scala-isolated-slick-example/app/models/UserRequest.scala, play-scala-isolated-slick-example/scripts/test-sbt
After the `reload` the Scala version gets set back to the default again.
So when running tests for Scala 3, having `MATRIX_SCALA=3.x` after the reload we are on Scala 2.13.x again...
I found this because I wanted to test Scala 3.3.7-RC2 locally and only published Play for that Scala 3 version and this test complained it can not find the 2.13.x artifacts...
=> Fix play-scala-isolated-slick-example test for Scala 3
